config/routes.rb
Rails.application.routes.draw do

    devise_for :admins, :controllers => { :registrations => 'admins/registrations', :sessions => 'admins/sessions'}
    devise_for :customers, :controllers => { :registrations => 'customers/registrations', :sessions => 'customers/sessions'}

    #admin
  namespace :admin do
    #homes
    root to: 'homes#top'

    #items
    resources :items, only:[:index, :new, :create, :show, :edit, :update]

    #genres
    resources :genres, only:[:index, :create, :edit, :update]

    #customers
    resources :customers, only:[:index, :show, :edit, :update]

    #orders
    resources :orders, only:[:show, :update]

    #oeder
    resources :order_items, only:[:update]

  end

    #public
  scope module: :public do

    #homes
    root to: 'homes#top'
    get '/about' => 'homes#about'

    #addresses
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]

    #orders
    get '/orders/thanks' => 'orders#thanks'
    post '/orders/verification' => 'orders#verification'
    resources :orders, only:[:index, :new, :show, :create]

    #cart_items
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index, :create, :update, :destroy]

    #customers
    get '/customers/verification' => 'customers#verification'
    patch '/customers/withdrawal' => 'customers#withdrawal'
    get '/customer/edit' => 'customers#edit', as: 'edit_customers'
    patch '/customer' => 'customers#update', as: 'update_customers'
    get '/customer' => 'customers#show', as: 'customers'

    #items
    get '/items' => 'items#index'
    get '/items/:id' => 'items#show', as: 'items_show'

  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses
  has_many :orders

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :email, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  #prepend_before_action :authenticate_scope!, except: [:edit]

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  #def new
  #   super
  #end

  # POST /resource/sign_in
  #def create
  #   super
  #end

  # DELETE /resource/sign_out
  #def destroy
  #   super
  #end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h2>会員情報編集</h2>

<%= form_with model:@customer, url:"/admin/customers/#{@customer.id}", local:true do |f| %>

 <h4>氏名</h4>
 <%= f.text_field :last_name %><%= f.text_field :first_name %>

 <h4>フリガナ</h4>
 <%= f.text_field :last_name_kana %> <%= f.text_field :first_name_kana %>

 <h4>郵便番号</h4>
 <%= f.text_field :postal_code %>

 <h4>住所</h4>
 <%= f.text_area :address %>

 <h4>電話番号</h4>
 <%= f.text_field :telephone_number %>

 <h4>メールアドレス</h4>
 <%= f.text_field :email %>

 <h4>会員ステータス</h4>
 <%= f.select :is_deleted, [["有効", true], ["退会", false]], include_blank: "選択して下さい" %>

 <%= f.submit '変更を保存' %>
<% end %>

app/views/admin/customers/index.html.erb
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <h2>会員一覧</h2>

      <table class="table">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @customers.each do |customer| %>
            <tr>
              <td><%= link_to customer.id, admin_customer_path(customer) %></td>
              <td><%= customer.last_name %><%= customer.first_name %></td>
              <td><%= customer.email %></td>
              <td>
                <% if customer.is_deleted == false %>
                有効
                <% else %>
                退会済み
                <% end %>
              </td>
            </tr>
            <% end %>

        </tbody>
      </table>
    </div>
  </div>

app/views/admin/customers/show.html.erb
<h2>会員詳細</h2>

<h4>会員ID</h4>
 <p><%= @customer.id %></p>

<h4>氏名</h4>
 <p><%= @customer.last_name %></p> <p><%= @customer.first_name %></p>

<h4>フリガナ</h4>
 <p><%= @customer.last_name_kana %></p> <p><%= @customer.first_name_kana %></p>

<h4>郵便番号</h4>
 <p><%= @customer.postal_code %></p>

<h4>住所</h4>
 <p><%= @customer.address %></p>

<h4>電話番号</h4>
 <p><%= @customer.telephone_number %></p>

<h4>メールアドレス</h4>
 <p><%= @customer.email %></p>

<h4>会員ステータス</h4>
 <p><%= @customer.is_deleted %></p>

<%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-info"%>
<%= link_to "注文一覧を見る", class: "btn btn-info"%>