config/routes.rb
Rails.application.routes.draw do

    devise_for :admins, :controllers => { :registrations => 'admins/registrations', :sessions => 'admins/sessions'}
    devise_for :customers, :controllers => { :registrations => 'customers/registrations', :sessions => 'customers/sessions'}

    #admin
  namespace :admin do
    #homes
    root to: 'homes#top'

    #items
    resources :items, only:[:index, :new, :create, :show, :edit, :update]

    #genres
    resources :genres, only:[:index, :create, :edit, :update]

    #customers
    resources :customers, only:[:index, :show, :edit, :update]

    #orders
    resources :orders, only:[:show, :update]

    #oeder
    resources :order_items, only:[:update]

  end

    #public
  scope module: :public do

    #homes
    root to: 'homes#top'
    get '/about' => 'homes#about'

    #addresses
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]

    #orders
    get '/orders/thanks' => 'orders#thanks'
    post '/orders/verification' => 'orders#verification'
    resources :orders, only:[:index, :new, :show, :create]

    #cart_items
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index, :create, :update, :destroy]

    #customers
    get '/customers/verification' => 'customers#verification'
    patch '/customers/withdrawal' => 'customers#withdrawal'
    get '/customer/edit' => 'customers#edit', as: 'edit_customers'
    patch '/customer' => 'customers#update', as: 'update_customers'
    get '/customer' => 'customers#show', as: 'customers'

    #items
    get '/items' => 'items#index'
    get '/items/:id' => 'items#show', as: 'items_show'

  end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses
  has_many :orders

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :order_details
  has_many :cart_items

  attachment :image

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details

  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

  enum making_status: { "着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :email, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path(@genre.id)
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path(@item.id)
  end

   private
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :genre_id, :is_active, :excluding_tax_price)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
    @ordered_item = @order.order_details
    @total = 0
    @ordered_item.each do |ordered_item|
    tol = ordered_item.item.excluding_tax_price * ordered_item.amount
    @total += tol
    end
  end

  def update
    @order = Order.find(params[:id])
    if params[:order][:status] == "b"
      order.ordered_items.each do |ordered_item|
        ordered_item.production_status = "b"
        ordered_item.update(production_status: ordered_item.production_status)
      end
    end
    order.update(order_params)
    redirect_to admin_order_path(order)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
    admin_root_path
    when Customer
    customers_path(resource)
    end
  end

  # def after_sign_out_path_for(resource)
  #   case resource
  #   when Admin
  #   new_admin_session_path
  #   when Customer
  #   root_path(resource)
  #   end
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :is_deleted])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<h2>ジャンル編集</h2>
<%= form_with model:@genre, url: admin_genre_path(@genre.id), local:true do |f| %>
  <h4>ジャンル名</h4>
  <%= f.text_field :name %>
  <%= f.submit '変更を保存' %>
<% end %>

app/views/admin/genres/index.html.erb
<h2>ジャンル一覧・追加<h2>
<!-- form_with部分 -->
<%= form_with model:@genre, url: admin_genres_path, local:true do |f| %>
  <h4>ジャンル名</h4>
  <%= f.text_field :name %> <%= f.submit '新規登録' %>
<% end %>

  <h4>ジャンル</h4>
  <% @genres.each do |genre| %>
   <p>
    <%= genre.name %> <%= link_to "編集する", edit_admin_genre_path(genre) %>
   </p>
  <% end %>

app/views/admin/items/edit.html.erb
<h2>商品編集</h2>

<%= form_with model:@item, url:"/admin/items/#{@item.id}", local:true do |f| %>

  <h4>商品画像</h4>
  <%= f.attachment_field :image %>

  <h4>商品名</h4>
  <%= f.text_field :name %>

  <h4>商品説明</h4>
  <%= f.text_area :introduction %>

  <h4>ジャンル</h4>
  <%= f.collection_select :genre_id, Genre.all, :id, :name %>

  <h4>税抜価格</h4>
  <%= f.text_field :excluding_tax_price %>

  <h4>販売ステータス</h4>
  <%= f.select :is_active, [["販売中", true], ["販売停止中", false]], include_blank: "選択して下さい" %>

  <%= f.submit '変更を保存' %>
<% end %>

app/views/admin/items/index.html.erb
<h2>商品一覧</h2>
<table class="table table-striped bg-light">
<tr>
  <th>商品名</th>
  <th>商品説明</th>
  <th>ジャンル</th>
  <th>税抜価格</th>
  <th>販売ステータス</th>
</tr>
<% @items.each do |item| %>
  <tr>
    <td><%= link_to item.name, admin_item_path(item) %></td>
    <td><%= item.introduction %>
    <td><%= item.genre.name %></td>
    <td><%= item.excluding_tax_price %></td>
    <td>
      <% if item.is_active %>
      販売中
      <% else %>
      販売停止中
      <% end %>
    </td>
  </tr>
<% end %>

<%= link_to "商品新規投稿", new_admin_item_path %>

app/views/admin/items/new.html.erb
<h1>商品新規登録</h1>
<div class="row">
<div class="col-xs-9">

<%= form_with model:@item, url: admin_items_path, local: true do |f| %>

 <h4>商品画像</h4>
 <%= f.attachment_field :image %>

 <h4>商品名</h4>
 <%= f.text_field :name %>

 <h4>商品説明</h4>
 <%= f.text_area :introduction %>

 <h4>ジャンル</h4>
 <%= f.collection_select :genre_id, Genre.all, :id, :name %>

 <h4>税抜価格</h4>
 <%= f.text_field :excluding_tax_price %>

 <h4>販売ステータス</h4>
 <%= f.select :is_active, [["販売中", true], ["販売停止中", false]], include_blank: "選択して下さい" %>

 <%= f.submit '新規投稿' %>

<% end %>

</div>
</div>

app/views/admin/items/show.html.erb
<h2>商品詳細</h2>

<div class="row">
  <div class="col-6">
    <%= attachment_image_tag @item, :image, format: 'jpeg', fallback: "no_img.jpg", style: "max-width: 100%"%>
  </div>
  <div class="col-6">
    <table class="table">
    <tr>
        <th>商品名</th>
        <td><%= @item.name%></td>
    </tr>
    <tr>
        <th>紹介文</th>
        <td><%= @item.introduction %></td>
    </tr>
    <tr>
        <th>ジャンル</th>
        <td><%= @item.genre.name %></td>
    </tr>
    <tr>
        <th>税抜価格</th>
        <td><%= @item.excluding_tax_price %></td>
    </tr>
    <tr>
        <th>販売ステータス</th>
        <td>
          <% if @item.is_active %>
          販売中
          <% else %>
          販売停止中
          <% end %>
        </td>
    </tr>
    </table>
     <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-info"%>
  </div>
</div>

app/views/admin/orders/show.html.erb
<h12注文履歴詳細 </h2>

<div>購入者 : <%= @order.customer.last_name %><%= @order.customer.first_name %></div>

<div>配送先 ：<%= @order.address %></div>

<div>支払い方法 :
<%= @order.payment_method %>
</div>

<!--注文ステータス :-->
<!--<%#= form_with model: @order, url: admin_order_path, local: true do |f| %>-->
<!--  <%#= f.select :status, Order.status %>-->
<!--  <%#= f.submit %>-->
<!--<%# end %>-->


<table border="1">
    <thead>
        <tr>
            <th>商品名</th>
            <th>単価</th>
            <th>数量</th>
            <th>小計</th>
            <!--<th>製作ステータス</th>-->
        </tr>
    </thead>
    <tbody>
        <% @ordered_item.each do |ordered_item| %>
            <tr>
                <td><%= ordered_item.item.name %></td>
                <td><%= ordered_item.item.excluding_tax_price %></td>
                <td><%= ordered_item.amount %></td>
                <td><%= ordered_item.item.excluding_tax_price * ordered_item.amount %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<div>商品合計 : <%= @total %></div>
<div>送料 : <%= @order.shipping_cost %></div>
<div>請求合計金額 : <%= @total + @order.shipping_cost %></div>