config/routes.rb
Rails.application.routes.draw do

    devise_for :admins, :controllers => { :registrations => 'admins/registrations', :sessions => 'admins/sessions'}
    devise_for :customers, :controllers => { :registrations => 'customers/registrations', :sessions => 'customers/sessions'}

    #admin
  namespace :admin do
    #homes
    root to: 'homes#top'

    #items
    resources :items, only:[:index, :new, :create, :show, :edit, :update]

    #genres
    resources :genres, only:[:index, :create, :edit, :update]

    #customers
    resources :customers, only:[:index, :show, :edit, :update]

    #orders
    resources :orders, only:[:show, :update]

    #oeder
    resources :order_items, only:[:update]

  end

    #public
  scope module: :public do

    #homes
    root to: 'homes#top'
    get '/about' => 'homes#about'

    #addresses
    resources :addresses, only:[:index, :edit, :create, :update, :destroy]

    #orders
    get '/orders/thanks' => 'orders#thanks'
    post '/orders/verification' => 'orders#verification'
    resources :orders, only:[:index, :new, :show, :create]

    #cart_items
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only:[:index, :create, :update, :destroy]

    #customers
    get '/customers/verification' => 'customers#verification'
    patch '/customers/withdrawal' => 'customers#withdrawal'
    get '/customer/edit' => 'customers#edit', as: 'edit_customers'
    patch '/customer' => 'customers#update', as: 'update_customers'
    get '/customer' => 'customers#show', as: 'customers'

    #items
    get '/items' => 'items#index'
    get '/items/:id' => 'items#show', as: 'items_show'

  end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items
  has_many :addresses
  has_many :orders

  def active_for_authentication?
    super && (self.is_deleted == false)
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :order_details
  has_many :cart_items

  attachment :image

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details

  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum status: { "入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :item
  belongs_to :order

  enum making_status: { "着手不可": 0, "製作待ち": 1, "製作中": 2, "製作完了": 3 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path(@genre.id)
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path(@item.id)
  end

   private
  def item_params
    params.require(:item).permit(:name, :image, :introduction, :genre_id, :is_active, :excluding_tax_price)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
    admin_root_path
    when Customer
    customers_path(resource)
    end
  end

  # def after_sign_out_path_for(resource)
  #   case resource
  #   when Admin
  #   new_admin_session_path
  #   when Customer
  #   root_path(resource)
  #   end
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :is_deleted])
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
      <%= link_to "ながのCAKE", root_path, class: "navbar-brand" %>

      <ul class="navbar-nav nav justify-content-end mr-sm-2">
        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to "商品一覧", admin_items_path %>
          </li>
          <li class="nav-item">
            <%= link_to "会員一覧", admin_customers_path %>
          </li>
          <li class="nav-item">
            <%= link_to "注文履歴一覧", admin_root_path %>
          </li>
          <li class="nav-item">
            <%= link_to "ジャンル一覧", admin_genres_path %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
          </li>

        <% elsif customer_signed_in? %>
        <li class="nav-item">
            <%= link_to "マイページ", customers_path %>
          </li>
          <li class="nav-item">
            <%= link_to "商品一覧", items_path %>
          </li>
          <li class="nav-item">
            <%= link_to "カート", cart_items_path %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_customer_session_path, method: :delete %>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to "About", about_path %>
          </li>
          <li class="nav-item">
            <%= link_to "商品一覧", items_path %>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_customer_registration_path %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_customer_session_path %>
          </li>
        <% end %>
      </ul>
      </div>
    </nav>
  </header>

  <body>
    <%= yield %>
  </body>
</html>